#!/usr/bin/env node
var jsdom = require('jsdom')

var selector =  process.argv[2]

var stdin = process.openStdin()
var buffer = ''
process.stdin.on('data', function(data){
  buffer += data
})

process.stdin.on('end', function(){
  jsdom.env(body, ['http://code.jquery.com/jquery-1.5.min.js'], function(e, window){
    console.log(window.$(selector).text())
  }
})
